/**
 * Generated by scripts/gen-revisions.mjs. Do not edit by hand.
 *
 * The last date on which each group of content sources actually changed, used
 * as <lastmod> in the sitemap and dateModified in the JSON-LD.
 */

/** Marketing, audience, reference and legal copy: src/lib/seo/content.ts. */
export const CONTENT_REVISED = '2026-09-05';

/** The typing tools: src/lib/seo/toolsContent.ts and toolsPages.ts. */
export const TOOLS_REVISED = '2026-09-05';
