-- The Arena Boards — one leaderboard for every mini game.
-- Design: docs/arena-leaderboards.md
--
-- This is the sibling of 20260814120000_daily_leaderboards.sql and inherits its
-- two governing rules verbatim, because they are the only reason a board of
-- strangers is safe to put in front of a nine-year-old:
--
--   1. A child's real name never leaves the household. The kid division's global
--      board shows `alias`, generated by Postgres from the profile id via
--      keytopia_alias(), so a tampered client cannot smuggle a real name onto a
--      stranger's screen. Teen and adult divisions show the name on the account,
--      because an adult owns theirs and a board of generated handles reads as a
--      placeholder rather than as people. See arena_public_name() below.
--
--   2. The client never states its own score. `score` is generated from
--      wpm/acc/value by arena_score(), and those three inputs are CHECK-clamped
--      to what a human hand can produce.
--
-- What is new here is shape, not policy. The Daily Challenge has one board per
-- day; the Arena has one per (game × period × division), and adding the ninth
-- game must not mean a ninth table. So: one table, one `period` bucket key, and
-- one CASE in one function.
--
-- As always, this is integrity, not anti-cheat. The run happens in a browser.
-- Clamps stop casual forgery; nothing here makes this a ranked ladder with
-- stakes, and the copy in the app never pretends otherwise.

-- ---------------------------------------------------------------------------
-- Which games may be ranked
-- ---------------------------------------------------------------------------
-- A table rather than a CHECK list so src/lib/arena.ts and the database can be
-- diffed against each other. `value_label` names each game's own headline count
-- ("blocks", "waves"); NULL hides that column on the board.
create table if not exists arena_games (
  id          text primary key,
  name        text not null,
  value_label text,
  active      boolean not null default true,
  sort        int not null default 100
);

insert into arena_games (id, name, value_label, sort) values
  ('lightstream', 'The Lightstream',  null,        10),
  ('duel',        'Quill Duel',       'rounds',    20),
  ('survivor',    'Survivor Sprint',  'heats',     30),
  ('wordfall',    'Wordfall Defence', 'waves',     40),
  ('stack',       'Block Stack',      'blocks',    50),
  ('cipher',      'Cipher Run',       'runes',     60),
  ('keyforge',    'Keyforge',         'treasures', 70),
  ('wordflight',  'Wordflight',       'gates',     80)
on conflict (id) do update
  set name = excluded.name, value_label = excluded.value_label, sort = excluded.sort;

-- ---------------------------------------------------------------------------
-- The score formula
-- ---------------------------------------------------------------------------
-- IMMUTABLE and pure so it can back a generated column, which is the whole
-- point: a client posts wpm/acc/value and Postgres decides what that is worth.
--
-- This is deliberately a migration per new game. The obvious alternative — a
-- formula string stored in arena_games — cannot back a generated column, and
-- the moment the formula is data it can be read by the client, which is halfway
-- to letting the client state its own score. The cost is one WHEN branch.
--
-- Each branch weights the game's own headline count first and uses typing
-- quality as the tiebreak, so the board rewards playing the game well rather
-- than hammering keys. Change a branch and the boards silently re-rank: add a
-- migration that also resets the affected `all` rows, or old and new scores sit
-- on the same board meaning different things.
create or replace function arena_score(p_game text, p_wpm real, p_acc real, p_value real)
returns integer
language sql
immutable
as $$
  select (case p_game
    -- The Lightstream ranks pace, with accuracy as the tiebreak. The 90%
    -- accuracy floor that makes this honest is enforced at submit time, not
    -- here: this function must stay total so a generated column never fails.
    when 'lightstream' then round(p_wpm * 10 + p_acc * 2)
    when 'duel'        then round(p_value * 200 + p_wpm * 5)
    when 'survivor'    then round(p_value * 150 + p_wpm * 5)
    when 'wordfall'    then round(p_value * 60 + p_acc * 6)
    when 'stack'       then round(p_value * 40 + p_acc * 4)
    when 'cipher'      then round(p_value * 50 + p_wpm * 3)
    when 'keyforge'    then round(p_value * 45 + p_wpm * 4)
    when 'wordflight'  then round(p_value * 55 + p_acc * 5)
    -- A game that reaches here has skipped step 1 of the checklist in
    -- docs/arena-leaderboards.md §10. It ranks on raw typing rather than
    -- erroring, so a missing branch is visible instead of a broken game.
    else round(p_wpm * 10 + p_acc)
  end)::integer;
$$;

-- ---------------------------------------------------------------------------
-- Scores
-- ---------------------------------------------------------------------------
create table if not exists arena_scores (
  game        text not null references arena_games (id),

  -- 'd:2026-08-16' | 'w:2026-W33' | 'all'. One row per learner per bucket, so
  -- today / this week / all time are the same query with a different key. Day
  -- and week keys are the CLIENT's local calendar, not the server's, because
  -- "today's board" is defined by the learner's own midnight — the same choice
  -- daily_scores.day_key makes, for the same reason.
  period      text not null check (period ~ '^(d:\d{4}-\d{2}-\d{2}|w:\d{4}-W\d{2}|all)$'),

  profile_id  text not null references profiles (id) on delete cascade,
  owner       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  age_group   text not null check (age_group in ('kid', 'teen', 'adult')),

  -- What a client may state.
  wpm         real not null check (wpm   >= 0 and wpm   <= 250),
  acc         real not null check (acc   >= 0 and acc   <= 100),
  value       real not null default 0 check (value >= 0 and value <= 100000),

  -- What it may not.
  score       integer not null generated always as (arena_score(game, wpm, acc, value)) stored,
  alias       text    not null generated always as (keytopia_alias(profile_id)) stored,

  -- Shown only on boards the learner was invited to.
  display_name text not null check (length(display_name) between 1 and 40),
  -- What the learner chose to be called on boards of strangers. Empty means
  -- "use the default for my division" (see arena_public_name). The charset is
  -- narrow on purpose: it is wide enough for a handle and too narrow to carry
  -- an email address, a URL or an @handle to somewhere else.
  board_name  text not null default '' check (
    board_name = '' or board_name ~ '^[A-Za-z0-9][A-Za-z0-9 ._-]{1,19}$'
  ),
  -- A built explorer encodes to a "ch1:k=knight,f=square,..." string, which
  -- reaches 98 characters fully customised and 67 for a stock preset. Bounded
  -- well above that: truncating one of these does not shorten a picture, it
  -- cuts a field in half and decodes to the wrong colour.
  avatar       text not null check (length(avatar) <= 160),

  -- The household's "hide global boards" setting, carried on the row rather
  -- than applied at read time. A setting that only hides is decoration: this
  -- row still backs the family board it was invited to, and is simply absent
  -- from the division board. See Settings.hideGlobalBoards.
  global      boolean not null default true,

  first_at    timestamptz not null default now(),
  -- When the BEST changed. This is a ranking input: ties break on the earlier
  -- posting, so a run that fails to improve must not touch it or the learner
  -- would silently lose tie-breaks by playing again.
  updated_at  timestamptz not null default now(),
  -- When a run was last posted at all, improving or not. Kept apart from
  -- updated_at precisely because it is bumped by every submission: it is what
  -- the rate limit reads, and a limiter that only sees improvements has a hole
  -- exactly the shape of a forger posting in a loop.
  last_at     timestamptz not null default now(),
  primary key (game, period, profile_id)
);

-- The board query is "one game, one bucket, one division, best first, earliest
-- wins ties". Covering it as an index keeps every board a single index scan.
create index if not exists arena_scores_board
  on arena_scores (game, period, age_group, score desc, updated_at asc);
create index if not exists arena_scores_by_profile
  on arena_scores (profile_id);
-- arena_home() looks up one learner's row in every game at once.
create index if not exists arena_scores_home
  on arena_scores (profile_id, period, game);

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------
-- Deliberately not "select to everyone". Cross-learner reads happen only
-- through the security-definer functions below, which decide what is safe to
-- reveal — so there is no path to a raw scan of every learner in the product.
alter table arena_scores enable row level security;
alter table arena_games  enable row level security;

drop policy if exists "own arena scores" on arena_scores;
create policy "own arena scores" on arena_scores
  for all to authenticated
  using (owner = auth.uid())
  with check (
    owner = auth.uid()
    and exists (select 1 from profiles p where p.id = profile_id and p.owner = auth.uid())
  );

-- Anonymous sessions exist so a child can claim a classroom seat without an
-- email. They carry the same `authenticated` role as a real household, so
-- without this a throwaway identity could post 249 wpm and sit at the top of a
-- division forever. RESTRICTIVE so it ANDs with the policy above rather than
-- offering a second way in. Writes only: a child on a school seat can still
-- watch a board, they just cannot compete on one full of strangers.
drop policy if exists "no anonymous arena scores" on arena_scores;
create policy "no anonymous arena scores" on arena_scores
  as restrictive
  for all to authenticated
  using (true)
  with check (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

-- The game list is a menu, not data about anyone.
drop policy if exists "anyone signed in reads the game list" on arena_games;
create policy "anyone signed in reads the game list" on arena_games
  for select to authenticated using (true);

-- ---------------------------------------------------------------------------
-- Who a board says you are
-- ---------------------------------------------------------------------------
-- A generated alias on every global board was the original rule, and for a
-- child it stays the rule: this product is used by eight-year-olds, and a board
-- of strangers carrying a real first name next to a score is a contact-discovery
-- surface, not a leaderboard. That has not stopped being true.
--
-- It was never true of the grown-up divisions in the same way. A teen or adult
-- owns their account, chose the name on it, and a board of "BraveHarbor05" reads
-- as a placeholder rather than as a person — which costs the board exactly the
-- realness that makes anyone care about their position on it. So the rule now
-- splits on the division rather than applying the strictest case to everybody.
--
-- `alias` stays a generated column regardless, because it is what the kid
-- division serves and a tampered client must never be able to influence it.
create or replace function arena_public_name(
  p_age text, p_alias text, p_display text, p_board text default ''
)
returns text
language sql
immutable
as $$
  select coalesce(
    -- A name someone chose beats both a generated handle and an account field:
    -- it is the only one of the three that is both real to them and not
    -- necessarily their real name. It is therefore also the answer for an adult
    -- who would rather not be identified, which the alias-or-real-name split
    -- did not offer anybody.
    nullif(trim(p_board), ''),
    case when p_age = 'kid' then p_alias else p_display end
  );
$$;

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------
-- Broadcast, not postgres_changes. RLS above is "own rows only", so change
-- events would deliver a learner nothing but their own writes — and a firehose
-- of every score in the product is the wrong shape regardless.
--
-- The payload carries only what the topic's audience can already see: an alias
-- and a score for a division board. No profile id, no owner, no display name.
-- Board-scope topics are not broadcast to at all; a family board is small
-- enough that the trailing refetch in src/lib/arenaLive.ts covers it, and
-- fanning out per membership would put a query in a hot write path.
create or replace function arena_broadcast()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Hidden-from-global rows are hidden here too, or the setting leaks the very
  -- thing it was set to suppress.
  if new.global then
    begin
      perform realtime.send(
        jsonb_build_object(
          -- The same division rule as the board reads. A broadcast that carried
          -- the alias while the board showed a real name would make a live row
          -- appear as a stranger and then rename itself on the next refetch.
          'alias', arena_public_name(new.age_group, new.alias, new.display_name, new.board_name),
          'avatar', case when new.age_group = 'kid' then '' else new.avatar end,
          'score', new.score,
          'wpm',   round(new.wpm)::int,
          'acc',   round(new.acc)::int,
          'value', new.value
        ),
        'score',
        'arena:' || new.game || ':' || new.period || ':' || new.age_group,
        true
      );
    exception when others then
      -- A board write must never fail because the realtime extension is
      -- missing, throttled, or mid-upgrade. The score is the durable thing;
      -- the broadcast is a nicety, and the client refetches on a timer anyway.
      null;
    end;
  end if;
  return new;
end;
$$;

drop trigger if exists arena_scores_broadcast on arena_scores;
create trigger arena_scores_broadcast
  after insert or update on arena_scores
  for each row execute function arena_broadcast();

-- ---------------------------------------------------------------------------
-- Reads
-- ---------------------------------------------------------------------------
-- The whole Arena hub in one round trip: one row per active game with the
-- learner's standing in it. `p_prev_period` is supplied by the client (which
-- already knows its own calendar) so this function never has to do date maths
-- for a timezone it cannot see.
create or replace function arena_home(
  p_profile_id  text,
  p_age         text,
  p_period      text,
  p_prev_period text default null
)
returns table (
  game        text,
  name        text,
  value_label text,
  your_score  int,
  your_value  real,
  your_rank   int,
  prev_rank   int,
  total       int,
  leader_name text,
  leader_score int
)
language sql
stable
security definer
set search_path = public
as $$
  select
    g.id,
    g.name,
    g.value_label,
    mine.score,
    mine.value,
    -- Rank as "how many are strictly ahead, plus one". Ties break on the
    -- earlier posting, matching rank() over (order by score desc, updated_at
    -- asc) in arena_board() — the two must agree or the hub and the board will
    -- show a learner two different positions.
    case when mine.score is null then null else (
      select count(*)::int + 1 from arena_scores s
      where s.game = g.id and s.period = p_period and s.age_group = p_age and s.global
        and (s.score > mine.score or (s.score = mine.score and s.updated_at < mine.updated_at))
    ) end,
    case when prev.score is null then null else (
      select count(*)::int + 1 from arena_scores s
      where s.game = g.id and s.period = p_prev_period and s.age_group = p_age and s.global
        and (s.score > prev.score or (s.score = prev.score and s.updated_at < prev.updated_at))
    ) end,
    (select count(*)::int from arena_scores s
      where s.game = g.id and s.period = p_period and s.age_group = p_age and s.global),
    lead.name,
    lead.score
  from arena_games g
  left join arena_scores mine
    on mine.game = g.id and mine.period = p_period and mine.profile_id = p_profile_id
  left join arena_scores prev
    on p_prev_period is not null
   and prev.game = g.id and prev.period = p_prev_period and prev.profile_id = p_profile_id
  left join lateral (
    select arena_public_name(s.age_group, s.alias, s.display_name, s.board_name) as name, s.score
    from arena_scores s
    where s.game = g.id and s.period = p_period and s.age_group = p_age and s.global
    order by s.score desc, s.updated_at asc
    limit 1
  ) lead on true
  where g.active
  order by g.sort;
$$;

-- One board. Returns the top N, plus the learner's own row when it fell outside
-- it, plus the rows immediately above and below them — so the "18 points to
-- reach #13" line needs no second call.
--
-- p_scope is 'global' (age division, aliases) or 'board' (an invited board from
-- 20260814120000_daily_leaderboards.sql, real names). Membership is re-checked
-- here rather than trusted from the client: this runs as definer and would
-- otherwise be an open read of any board's scores.
create or replace function arena_board(
  p_game       text,
  p_period     text,
  p_scope      text,
  p_board_id   uuid default null,
  p_age        text default null,
  p_profile_id text default null,
  p_limit      int  default 10,
  -- Paging is "show me the next ten", not numbered pages: a leaderboard's
  -- meaning lives at the top and around your own row, and page 7 of 41 is a
  -- place nobody navigates to on purpose.
  p_offset     int  default 0
)
returns table (
  rank int, name text, avatar text,
  wpm real, acc real, value real, score int,
  you boolean, neighbour boolean, total int
)
language sql
stable
security definer
set search_path = public
as $$
  with pop as (
    select s.* from arena_scores s
    where s.game = p_game and s.period = p_period
      and case
        when p_scope = 'global' then s.age_group = p_age and s.global
        else is_board_member(p_board_id)
             and exists (
               select 1 from board_members m
               where m.board_id = p_board_id and m.profile_id = s.profile_id
             )
      end
  ),
  ranked as (
    select
      rank() over (order by p.score desc, p.updated_at asc)::int as rank,
      case when p_scope = 'global'
        then arena_public_name(p.age_group, p.alias, p.display_name, p.board_name)
        else p.display_name end as name,
      -- A kid's chosen avatar is part of how they present themselves, so it is
      -- withheld from strangers too; the board draws a neutral one instead.
      case when p_scope = 'global' and p.age_group = 'kid' then '' else p.avatar end as avatar,
      p.wpm, p.acc, p.value, p.score,
      (p.profile_id is not distinct from p_profile_id) as you
    from pop p
  ),
  mine as (select r.rank from ranked r where r.you),
  -- Counted once over the whole population, so the caller can tell "that is
  -- everybody" from "there is another page" without a second round trip.
  size as (select count(*)::int as n from ranked)
  select r.rank, r.name, r.avatar, r.wpm, r.acc, r.value, r.score, r.you,
         coalesce(abs(r.rank - m.rank) = 1, false),
         size.n
  from ranked r left join mine m on true cross join size
  where (r.rank > greatest(p_offset, 0) and r.rank <= greatest(p_offset, 0) + greatest(p_limit, 1))
     or r.you
     or coalesce(abs(r.rank - m.rank) <= 1, false)
  order by r.rank;
$$;

-- ---------------------------------------------------------------------------
-- Writes
-- ---------------------------------------------------------------------------
-- Post one run and get the finish screen back in the same response.
--
-- This is the function the whole rank-reveal design rests on. It writes the
-- day, week and all-time rows, and returns for each of them the new rank, the
-- rank before this run, how many people were overtaken and the nearest one's
-- name, and the gap to the rung above. The client therefore paints the reveal
-- from one round trip: no polling, no second fetch, no flicker.
--
-- Ranks reported here are always the GLOBAL division board, because that is the
-- board the reveal shows. A learner reading their family board sees it re-rank
-- through the realtime path instead.
create or replace function arena_submit(
  p_game       text,
  p_profile_id text,
  p_age        text,
  p_wpm        real,
  p_acc        real,
  p_value      real,
  p_name       text,
  p_avatar     text,
  p_day        text,
  p_week       text,
  p_global     boolean default true,
  p_board_name text default ''
)
returns table (
  period      text,
  score       int,
  best        int,
  improved    boolean,
  rank        int,
  prev_rank   int,
  passed      int,
  passed_name text,
  total       int,
  next_rank   int,
  next_gap    int
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_periods text[];
  v_period  text;
  v_run     int;
  v_prev    arena_scores%rowtype;
  v_now     arena_scores%rowtype;
  v_prev_rank int;
  v_rank      int;
begin
  -- Definer rights bypass RLS entirely, so the restrictive anonymous policy
  -- above does nothing in here. Every definer function has to repeat it.
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then
    raise exception 'anonymous sessions cannot post scores';
  end if;
  if not exists (select 1 from profiles p where p.id = p_profile_id and p.owner = auth.uid()) then
    raise exception 'profile does not belong to this account';
  end if;
  if not exists (select 1 from arena_games g where g.id = p_game and g.active) then
    raise exception 'unknown game';
  end if;

  -- The accuracy floor that makes the Lightstream board one honest number
  -- whatever you raced: a CPU race, a ghost race and a room race all post here,
  -- so a sloppy sprint must not outrank a clean one. The run is still saved
  -- locally and still counts toward the race record; it just does not post.
  if p_game = 'lightstream' and p_acc < 90 then
    return;
  end if;

  -- A run cannot legitimately finish this fast, and a loop that can is the
  -- cheapest possible forgery. Silent rather than an error: the caller is
  -- fire-and-forget and a thrown exception would be noise on a finish screen.
  if exists (
    select 1 from arena_scores s
    where s.game = p_game and s.profile_id = p_profile_id and s.period = 'all'
      and s.last_at > now() - interval '3 seconds'
  ) then
    return;
  end if;

  v_run := arena_score(p_game, p_wpm, p_acc, p_value);
  v_periods := array['d:' || p_day, 'w:' || p_week, 'all'];

  foreach v_period in array v_periods loop
    select * into v_prev from arena_scores s
      where s.game = p_game and s.period = v_period and s.profile_id = p_profile_id;

    -- The learner's row in a bucket is their best in it. Postgres cannot express
    -- that in the upsert (score is generated, so it cannot be read in the WHERE
    -- of the same statement), which is why the comparison happens here.
    v_prev_rank := null;
    if v_prev.profile_id is not null then
      select count(*)::int + 1 into v_prev_rank from arena_scores s
        where s.game = p_game and s.period = v_period and s.age_group = p_age and s.global
          and (s.score > v_prev.score or (s.score = v_prev.score and s.updated_at < v_prev.updated_at));
    end if;

    insert into arena_scores as a
      (game, period, profile_id, age_group, wpm, acc, value, display_name, avatar, board_name, global, updated_at)
    values
      (p_game, v_period, p_profile_id, p_age,
       greatest(0, least(250, p_wpm)),
       greatest(0, least(100, p_acc)),
       greatest(0, least(100000, p_value)),
       left(p_name, 40), left(p_avatar, 160),
       -- Silently dropped rather than rejected when it does not fit the
       -- charset: a finish screen is the wrong place to argue about a name.
       case when trim(coalesce(p_board_name, '')) ~ '^[A-Za-z0-9][A-Za-z0-9 ._-]{1,19}$'
            then trim(p_board_name) else '' end,
       p_global, now())
    -- Inferred by constraint name rather than by column list: `period` is
    -- also an OUT parameter of this function, and an ON CONFLICT column list
    -- cannot tell the two apart.
    on conflict on constraint arena_scores_pkey do update
      -- The run only takes the row when it beat what was there: the learner's
      -- row in a bucket is their best in it. `excluded.score` cannot carry the
      -- comparison because score is generated, so v_run does.
      set wpm        = case when v_run > a.score then excluded.wpm   else a.wpm   end,
          acc        = case when v_run > a.score then excluded.acc   else a.acc   end,
          value      = case when v_run > a.score then excluded.value else a.value end,
          -- Ties break on the earlier posting, so a run that did not improve
          -- must leave this alone.
          updated_at = case when v_run > a.score then now() else a.updated_at end,
          -- Who you are refreshes on every run, improving or not. These are not
          -- results, they are how you appear: an explorer you just rebuilt, a
          -- board name you just chose, or a household that just switched global
          -- boards off would otherwise sit stale on the board until the day you
          -- happened to beat your own record.
          display_name = excluded.display_name,
          avatar       = excluded.avatar,
          board_name   = excluded.board_name,
          global       = excluded.global;

    -- Stamped on every run, improving or not, so the rate limit above sees
    -- attempts rather than only successes.
    update arena_scores s set last_at = now()
      where s.game = p_game and s.period = v_period and s.profile_id = p_profile_id;

    select * into v_now from arena_scores s
      where s.game = p_game and s.period = v_period and s.profile_id = p_profile_id;

    select count(*)::int + 1 into v_rank from arena_scores s
      where s.game = p_game and s.period = v_period and s.age_group = p_age and s.global
        and (s.score > v_now.score or (s.score = v_now.score and s.updated_at < v_now.updated_at));

    period      := v_period;
    score       := v_run;
    best        := v_now.score;
    improved    := (v_prev.profile_id is null or v_run > v_prev.score);
    rank        := v_rank;
    prev_rank   := v_prev_rank;
    passed      := greatest(0, coalesce(v_prev_rank, 0) - v_rank);

    -- The nearest person overtaken is whoever now sits directly below you.
    select arena_public_name(s.age_group, s.alias, s.display_name, s.board_name) into passed_name
    from arena_scores s
      where s.game = p_game and s.period = v_period and s.age_group = p_age and s.global
        and (s.score < v_now.score or (s.score = v_now.score and s.updated_at > v_now.updated_at))
      order by s.score desc, s.updated_at asc limit 1;
    if coalesce(passed, 0) = 0 then passed_name := null; end if;

    select count(*)::int into total from arena_scores s
      where s.game = p_game and s.period = v_period and s.age_group = p_age and s.global;

    -- The rung above, and what it costs. This is the line the whole design is
    -- built around, so it is computed here rather than inferred by the client.
    if v_rank > 1 then
      select v_rank - 1, greatest(1, s.score - v_now.score + 1)
        into next_rank, next_gap
      from arena_scores s
      where s.game = p_game and s.period = v_period and s.age_group = p_age and s.global
        and (s.score > v_now.score or (s.score = v_now.score and s.updated_at < v_now.updated_at))
      order by s.score asc, s.updated_at desc limit 1;
    else
      next_rank := null; next_gap := null;
    end if;

    return next;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
-- RLS decides which rows, grants decide whether the role may address the table
-- at all, and both gates must be open.
grant select, insert, update, delete on table arena_scores to authenticated;
grant select                        on table arena_games  to authenticated;

-- Postgres grants EXECUTE to PUBLIC on every newly created function, and PUBLIC
-- includes `anon`. Granting to `authenticated` alone therefore changes nothing:
-- the door was already open and a signed-out visitor could read every board.
-- Revoke first, then grant. The order is the entire point.
revoke execute on function arena_score(text, real, real, real)                     from public;
revoke execute on function arena_home(text, text, text, text)                      from public;
revoke execute on function arena_board(text, text, text, uuid, text, text, int, int) from public;
revoke execute on function arena_submit(text, text, text, real, real, real, text, text, text, text, boolean, text) from public;
revoke execute on function arena_broadcast()                                       from public;
revoke execute on function arena_public_name(text, text, text, text)               from public;

grant execute on function arena_home(text, text, text, text)                       to authenticated;
grant execute on function arena_board(text, text, text, uuid, text, text, int, int) to authenticated;
grant execute on function arena_submit(text, text, text, real, real, real, text, text, text, text, boolean, text) to authenticated;
-- arena_score MUST be executable by the inserting role. A generated column is
-- evaluated with the privileges of whoever runs the INSERT, not the table
-- owner, so revoking this from `authenticated` does not hide the function — it
-- makes every score submission fail with "permission denied for function
-- arena_score". Revoked from PUBLIC above, granted back here. The identical
-- trap cost a day on keytopia_alias(); it is the same trap.
grant execute on function arena_score(text, real, real, real)                      to authenticated;
grant execute on function arena_public_name(text, text, text, text)                to authenticated;

-- `anon` gets nothing: signed-out visitors never appear on, or read, a board.
